import Foundation
import WebKit

// MARK: - Navigation Decider

/// Intercepts link taps in the reader WebView and opens external URLs
/// in the system browser instead of navigating in-place.
///
/// Also intercepts `stower-embed://{urlencoded URL}` custom-scheme links
/// emitted by `ReaderDocumentHTMLBuilder` for inline embed expansion.
struct ReaderNavigationDecider: WebPage.NavigationDeciding {
    var openExternalURL: @MainActor (URL) -> Void
    var openInlineEmbed: @MainActor (String) -> Void
    var toggleChrome: @MainActor () -> Void

    @MainActor
    mutating func decidePolicy(
        for action: WebPage.NavigationAction,
        preferences: inout WebPage.NavigationPreferences
    ) async -> WKNavigationActionPolicy {
        guard let url = action.request.url else { return .allow }

        // Custom scheme for inline-expandable embeds generated by the HTML builder.
        if url.scheme == "stower-embed" {
            // Recover the original URL after the builder's percent-encoding.
            let raw = url.absoluteString
                .replacingOccurrences(of: "stower-embed://", with: "")
            let decoded = raw.removingPercentEncoding ?? raw
            openInlineEmbed(decoded)
            return .cancel
        }

        if url.scheme == "stower-reader",
           url.host(percentEncoded: false) == "toggle-chrome" {
            toggleChrome()
            return .cancel
        }

        let host = url.host(percentEncoded: false)
        if host == "localhost" || url.scheme == "about" || url.scheme == "blob" {
            return .allow
        }

        if action.navigationType == .linkActivated,
           url.scheme == "https" || url.scheme == "http" {
            openExternalURL(url)
            return .cancel
        }

        return .allow
    }
}

// MARK: - WebPage Factory

/// Creates configured `WebPage` instances for the reader.
enum ReaderWebPageFactory {
    /// Creates a new `WebPage` with link interception.
    /// CSS is injected directly into the HTML before loading — no WKUserScript needed.
    @MainActor
    static func makePage(
        openExternalURL: @MainActor @escaping (URL) -> Void,
        openInlineEmbed: @MainActor @escaping (String) -> Void = { _ in },
        toggleChrome: @MainActor @escaping () -> Void = {}
    ) -> WebPage {
        let decider = ReaderNavigationDecider(
            openExternalURL: openExternalURL,
            openInlineEmbed: openInlineEmbed,
            toggleChrome: toggleChrome
        )
        return WebPage(navigationDecider: decider)
    }

    static let contentTapScript = """
        (function() {
            if (window.__stowerContentTapHandlerInstalled) { return; }
            window.__stowerContentTapHandlerInstalled = true;

            var toggleURL = 'stower-reader://toggle-chrome';
            var interactiveSelector = 'a, button, input, textarea, select, option, label, summary, details, iframe, video, audio, [contenteditable=\"true\"], .stower-yt-facade';

            document.addEventListener('click', function(e) {
                if (e.defaultPrevented) { return; }
                if (window.getSelection && String(window.getSelection()).length > 0) { return; }

                var target = e.target;
                if (!target || !target.closest) { return; }
                if (target.closest(interactiveSelector)) { return; }

                window.location.href = toggleURL;
            });
        })();
        """

    @MainActor
    static func installReaderRuntime(on page: WebPage) async {
        let script = """
            (() => {
              var currentHighlight = null;
              window.stowerHighlight = function(index) {
                if (currentHighlight) currentHighlight.classList.remove('stower-highlight');
                currentHighlight = null;
                if (index == null || index < 0) return;
                const el = document.querySelector('[data-block-index="' + index + '"]');
                if (!el) return;
                el.classList.add('stower-highlight'); currentHighlight = el;
                const rect = el.getBoundingClientRect();
                if (rect.top < 60 || rect.bottom > innerHeight - 60) el.scrollIntoView({behavior:'smooth',block:'start'});
              };
              window.stowerScrollToBlock = function(index) {
                const el = document.querySelector('[data-block-index="' + index + '"]');
                if (el) el.scrollIntoView({behavior:'auto',block:'start'});
              };
              window.stowerGetTopBlockIndex = function() {
                const blocks = document.querySelectorAll('[data-block-index]');
                for (const block of blocks) {
                  if (block.getBoundingClientRect().bottom >= 80) {
                    const value = parseInt(block.dataset.blockIndex, 10);
                    if (!Number.isNaN(value)) return value;
                  }
                }
                return -1;
              };
            })();
            """
        _ = try? await page.callJavaScript(script)
    }

    /// Highlights the block with the given index (or clears all highlights if nil).
    @MainActor
    static func runHighlight(_ index: Int?, on page: WebPage) async {
        let idxJS: String
        if let index, index >= 0 {
            idxJS = String(index)
        } else {
            idxJS = "null"
        }
        _ = try? await page.callJavaScript("window.stowerHighlight(\(idxJS));")
    }

    /// Jumps to a block without animation — used to restore last-read position.
    @MainActor
    static func scrollToBlock(_ index: Int, on page: WebPage) async {
        guard index > 0 else { return }
        let script = """
        if (typeof window.stowerScrollToBlock === 'function') {
            window.stowerScrollToBlock(\(index));
        }
        """
        _ = try? await page.callJavaScript(script)
    }

    /// Returns the data-block-index of the topmost visible block, or nil on failure.
    ///
    /// Guards the call with `typeof` so pages that don't expose
    /// `stowerGetTopBlockIndex()` (e.g. user-imported website archives that
    /// Stower didn't author) return a clean nil instead of spewing JS
    /// exceptions into the WebContent log each poll tick.
    @MainActor
    static func fetchTopBlockIndex(on page: WebPage) async -> Int? {
        let script = """
        return typeof window.stowerGetTopBlockIndex === 'function'
            ? window.stowerGetTopBlockIndex()
            : null;
        """
        let result = try? await page.callJavaScript(script)
        guard let number = result as? Int else { return nil }
        return number >= 0 ? number : nil
    }

    /// Updates reader CSS on a live page without reloading.
    /// Used for live theme/font changes after the page is already loaded.
    @MainActor
    static func updateCSS(_ css: String, on page: WebPage) async {
        // JSON-encode the CSS for safe embedding in JS
        let jsonData = (try? JSONSerialization.data(
            withJSONObject: css,
            options: .fragmentsAllowed
        )) ?? Data("\"\"".utf8)
        let jsLiteral = String(data: jsonData, encoding: .utf8) ?? "\"\""

        let script = """
            (function() {
                var style = document.getElementById('stower-reader-css');
                if (!style) {
                    style = document.createElement('style');
                    style.id = 'stower-reader-css';
                    (document.head || document.documentElement).appendChild(style);
                }
                style.textContent = \(jsLiteral);
            })();
            """
        _ = try? await page.callJavaScript(script)
    }

    @MainActor
    static func installContentTapHandler(on page: WebPage) async {
        _ = try? await page.callJavaScript(contentTapScript)
    }

    /// For user-imported website archives, when the rendered document
    /// already fits within the viewport we want the WebView to stop
    /// interpreting horizontal swipes as scroll-the-page gestures — those
    /// gestures should reach interactive widgets (carousels, draggable
    /// cards, swipe menus) inside the page instead of being eaten by the
    /// outer scroll view's bounce.
    ///
    /// The script watches for `resize` / DOM mutations and toggles
    /// `overflow-x` and `touch-action` on `<html>`/`<body>` depending on
    /// whether the document actually overflows. When it doesn't, vertical
    /// pan + pinch-zoom stay enabled but horizontal pans are released to
    /// the page's own handlers. Sites wider than the viewport keep their
    /// normal horizontal scroll.
    static let horizontalScrollLockScript = """
        (function() {
            if (window.__stowerHorizontalLockInstalled) { return; }
            window.__stowerHorizontalLockInstalled = true;

            var root = document.documentElement;
            var body = document.body;

            function apply() {
                if (!body) { body = document.body; }
                if (!body) { return; }
                var fits = root.scrollWidth <= window.innerWidth + 1;
                if (fits) {
                    root.style.overflowX = 'hidden';
                    body.style.overflowX = 'hidden';
                    body.style.touchAction = 'pan-y pinch-zoom';
                } else {
                    root.style.overflowX = '';
                    body.style.overflowX = '';
                    body.style.touchAction = '';
                }
            }

            apply();
            window.addEventListener('resize', apply);
            window.addEventListener('orientationchange', apply);
            if (window.ResizeObserver) {
                var ro = new ResizeObserver(apply);
                ro.observe(root);
            }
        })();
        """

    @MainActor
    static func installHorizontalScrollLock(on page: WebPage) async {
        _ = try? await page.callJavaScript(horizontalScrollLockScript)
    }
}
