import Foundation
import WebKit

// MARK: - Navigation Decider

/// Intercepts link taps in the reader WebView and opens external URLs
/// in the system browser instead of navigating in-place.
///
/// Also intercepts `stower-embed://{urlencoded URL}` custom-scheme links
/// emitted by `ReaderDocumentHTMLBuilder` for inline embed expansion.
struct ReaderNavigationDecider: WebPage.NavigationDeciding {
    var openExternalURL: @MainActor (URL) -> Void
    var openInlineEmbed: @MainActor (String) -> Void

    @MainActor
    mutating func decidePolicy(
        for action: WebPage.NavigationAction,
        preferences: inout WebPage.NavigationPreferences
    ) async -> WKNavigationActionPolicy {
        guard let url = action.request.url else { return .allow }

        // Custom scheme for inline-expandable embeds generated by the HTML builder.
        if url.scheme == "stower-embed" {
            // Recover the original URL after the builder's percent-encoding.
            let raw = url.absoluteString
                .replacingOccurrences(of: "stower-embed://", with: "")
            let decoded = raw.removingPercentEncoding ?? raw
            openInlineEmbed(decoded)
            return .cancel
        }

        let host = url.host(percentEncoded: false)
        if host == "localhost" || url.scheme == "about" || url.scheme == "blob" {
            return .allow
        }

        if action.navigationType == .linkActivated,
           url.scheme == "https" || url.scheme == "http" {
            openExternalURL(url)
            return .cancel
        }

        return .allow
    }
}

// MARK: - WebPage Factory

/// Creates configured `WebPage` instances for the reader.
enum ReaderWebPageFactory {

    /// Creates a new `WebPage` with link interception.
    /// CSS is injected directly into the HTML before loading — no WKUserScript needed.
    @MainActor
    static func makePage(
        openExternalURL: @MainActor @escaping (URL) -> Void,
        openInlineEmbed: @MainActor @escaping (String) -> Void = { _ in }
    ) -> WebPage {
        let decider = ReaderNavigationDecider(
            openExternalURL: openExternalURL,
            openInlineEmbed: openInlineEmbed
        )
        return WebPage(navigationDecider: decider)
    }

    /// Highlights the block with the given index (or clears all highlights if nil).
    @MainActor
    static func runHighlight(_ index: Int?, on page: WebPage) async {
        let idxJS: String
        if let index, index >= 0 {
            idxJS = String(index)
        } else {
            idxJS = "null"
        }
        _ = try? await page.callJavaScript("window.stowerHighlight(\(idxJS));")
    }

    /// Jumps to a block without animation — used to restore last-read position.
    @MainActor
    static func scrollToBlock(_ index: Int, on page: WebPage) async {
        guard index > 0 else { return }
        _ = try? await page.callJavaScript("window.stowerScrollToBlock(\(index));")
    }

    /// Returns the data-block-index of the topmost visible block, or nil on failure.
    @MainActor
    static func fetchTopBlockIndex(on page: WebPage) async -> Int? {
        let result = try? await page.callJavaScript("return window.stowerGetTopBlockIndex();")
        guard let number = result as? Int else { return nil }
        return number >= 0 ? number : nil
    }

    /// Updates reader CSS on a live page without reloading.
    /// Used for live theme/font changes after the page is already loaded.
    @MainActor
    static func updateCSS(_ css: String, on page: WebPage) async {
        // JSON-encode the CSS for safe embedding in JS
        let jsonData = (try? JSONSerialization.data(
            withJSONObject: css,
            options: .fragmentsAllowed
        )) ?? Data("\"\"".utf8)
        let jsLiteral = String(data: jsonData, encoding: .utf8) ?? "\"\""

        let script = """
            (function() {
                var style = document.getElementById('stower-reader-css');
                if (!style) {
                    style = document.createElement('style');
                    style.id = 'stower-reader-css';
                    (document.head || document.documentElement).appendChild(style);
                }
                style.textContent = \(jsLiteral);
            })();
            """
        _ = try? await page.callJavaScript(script)
    }
}
